@base_URL=http://localhost:3000/api/locations

get {{base_URL}}

###
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjVlZTA5ZWZkMjQyMzEwMWZhYzc1OGQiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MTc0OTM5MzQsImV4cCI6MTcxNzQ5NzUzNH0.TuA4QsQpemdmVKibrop7jds38-x0IBhwkKZj9APujw4
post {{base_URL}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "name": "Loods Casier",
    "address": "Kloostermolenstraat 2, 8650 Merkem"
}

###
get {{base_URL}}
Content-Type: application/json

###
@objId=664f090599cf7815108265f2
get {{base_URL}}
Content-Type: application/json
